//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace my_progect.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Business", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Business : my_progect.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private my_progect.ServiceReference1.Categories CategoriesidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Image1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Image2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Image3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private my_progect.ServiceReference1.Seller SelleridField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public my_progect.ServiceReference1.Categories Categoriesid {
            get {
                return this.CategoriesidField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriesidField, value) != true)) {
                    this.CategoriesidField = value;
                    this.RaisePropertyChanged("Categoriesid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image1 {
            get {
                return this.Image1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Image1Field, value) != true)) {
                    this.Image1Field = value;
                    this.RaisePropertyChanged("Image1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image2 {
            get {
                return this.Image2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Image2Field, value) != true)) {
                    this.Image2Field = value;
                    this.RaisePropertyChanged("Image2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image3 {
            get {
                return this.Image3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Image3Field, value) != true)) {
                    this.Image3Field = value;
                    this.RaisePropertyChanged("Image3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public my_progect.ServiceReference1.Seller Sellerid {
            get {
                return this.SelleridField;
            }
            set {
                if ((object.ReferenceEquals(this.SelleridField, value) != true)) {
                    this.SelleridField = value;
                    this.RaisePropertyChanged("Sellerid");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntity", Namespace="http://schemas.datacontract.org/2004/07/modle")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(my_progect.ServiceReference1.Categories))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(my_progect.ServiceReference1.People))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(my_progect.ServiceReference1.City))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(my_progect.ServiceReference1.Seller))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(my_progect.ServiceReference1.Costumer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(my_progect.ServiceReference1.Comments))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(my_progect.ServiceReference1.Takendates))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(my_progect.ServiceReference1.Chat))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(my_progect.ServiceReference1.Business))]
    public partial class BaseEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Categories", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Categories : my_progect.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="People", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(my_progect.ServiceReference1.Seller))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(my_progect.ServiceReference1.Costumer))]
    public partial class People : my_progect.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private my_progect.ServiceReference1.City C1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public my_progect.ServiceReference1.City C1 {
            get {
                return this.C1Field;
            }
            set {
                if ((object.ReferenceEquals(this.C1Field, value) != true)) {
                    this.C1Field = value;
                    this.RaisePropertyChanged("C1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Firstname {
            get {
                return this.FirstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstnameField, value) != true)) {
                    this.FirstnameField = value;
                    this.RaisePropertyChanged("Firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lastname {
            get {
                return this.LastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastnameField, value) != true)) {
                    this.LastnameField = value;
                    this.RaisePropertyChanged("Lastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="City", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class City : my_progect.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Seller", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Seller : my_progect.ServiceReference1.People {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Costumer", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Costumer : my_progect.ServiceReference1.People {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Comments", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Comments : my_progect.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private my_progect.ServiceReference1.Business BusinessidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private my_progect.ServiceReference1.Costumer CostumeridField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public my_progect.ServiceReference1.Business Businessid {
            get {
                return this.BusinessidField;
            }
            set {
                if ((object.ReferenceEquals(this.BusinessidField, value) != true)) {
                    this.BusinessidField = value;
                    this.RaisePropertyChanged("Businessid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public my_progect.ServiceReference1.Costumer Costumerid {
            get {
                return this.CostumeridField;
            }
            set {
                if ((object.ReferenceEquals(this.CostumeridField, value) != true)) {
                    this.CostumeridField = value;
                    this.RaisePropertyChanged("Costumerid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Takendates", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Takendates : my_progect.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private my_progect.ServiceReference1.Seller SelleridField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TakendateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public my_progect.ServiceReference1.Seller Sellerid {
            get {
                return this.SelleridField;
            }
            set {
                if ((object.ReferenceEquals(this.SelleridField, value) != true)) {
                    this.SelleridField = value;
                    this.RaisePropertyChanged("Sellerid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Takendate {
            get {
                return this.TakendateField;
            }
            set {
                if ((this.TakendateField.Equals(value) != true)) {
                    this.TakendateField = value;
                    this.RaisePropertyChanged("Takendate");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Chat", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Chat : my_progect.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private my_progect.ServiceReference1.Business BusinessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ChatDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private my_progect.ServiceReference1.People PeopleAcceptField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private my_progect.ServiceReference1.People PeopleWriterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ReadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarksField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public my_progect.ServiceReference1.Business Business {
            get {
                return this.BusinessField;
            }
            set {
                if ((object.ReferenceEquals(this.BusinessField, value) != true)) {
                    this.BusinessField = value;
                    this.RaisePropertyChanged("Business");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ChatDate {
            get {
                return this.ChatDateField;
            }
            set {
                if ((this.ChatDateField.Equals(value) != true)) {
                    this.ChatDateField = value;
                    this.RaisePropertyChanged("ChatDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public my_progect.ServiceReference1.People PeopleAccept {
            get {
                return this.PeopleAcceptField;
            }
            set {
                if ((object.ReferenceEquals(this.PeopleAcceptField, value) != true)) {
                    this.PeopleAcceptField = value;
                    this.RaisePropertyChanged("PeopleAccept");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public my_progect.ServiceReference1.People PeopleWriter {
            get {
                return this.PeopleWriterField;
            }
            set {
                if ((object.ReferenceEquals(this.PeopleWriterField, value) != true)) {
                    this.PeopleWriterField = value;
                    this.RaisePropertyChanged("PeopleWriter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Read {
            get {
                return this.ReadField;
            }
            set {
                if ((this.ReadField.Equals(value) != true)) {
                    this.ReadField = value;
                    this.RaisePropertyChanged("Read");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remarks {
            get {
                return this.RemarksField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarksField, value) != true)) {
                    this.RemarksField = value;
                    this.RaisePropertyChanged("Remarks");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAllbusiness", ReplyAction="http://tempuri.org/IService1/SelectAllbusinessResponse")]
        my_progect.ServiceReference1.Business[] SelectAllbusiness();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAllbusiness", ReplyAction="http://tempuri.org/IService1/SelectAllbusinessResponse")]
        System.Threading.Tasks.Task<my_progect.ServiceReference1.Business[]> SelectAllbusinessAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectByIdbusiness", ReplyAction="http://tempuri.org/IService1/SelectByIdbusinessResponse")]
        my_progect.ServiceReference1.Business SelectByIdbusiness(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectByIdbusiness", ReplyAction="http://tempuri.org/IService1/SelectByIdbusinessResponse")]
        System.Threading.Tasks.Task<my_progect.ServiceReference1.Business> SelectByIdbusinessAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Insertbusiness", ReplyAction="http://tempuri.org/IService1/InsertbusinessResponse")]
        void Insertbusiness(my_progect.ServiceReference1.Business p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Insertbusiness", ReplyAction="http://tempuri.org/IService1/InsertbusinessResponse")]
        System.Threading.Tasks.Task InsertbusinessAsync(my_progect.ServiceReference1.Business p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Updatebusiness", ReplyAction="http://tempuri.org/IService1/UpdatebusinessResponse")]
        void Updatebusiness(my_progect.ServiceReference1.Business p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Updatebusiness", ReplyAction="http://tempuri.org/IService1/UpdatebusinessResponse")]
        System.Threading.Tasks.Task UpdatebusinessAsync(my_progect.ServiceReference1.Business p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAllcategories", ReplyAction="http://tempuri.org/IService1/SelectAllcategoriesResponse")]
        my_progect.ServiceReference1.Categories[] SelectAllcategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAllcategories", ReplyAction="http://tempuri.org/IService1/SelectAllcategoriesResponse")]
        System.Threading.Tasks.Task<my_progect.ServiceReference1.Categories[]> SelectAllcategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectByIdcategories", ReplyAction="http://tempuri.org/IService1/SelectByIdcategoriesResponse")]
        my_progect.ServiceReference1.Categories SelectByIdcategories(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectByIdcategories", ReplyAction="http://tempuri.org/IService1/SelectByIdcategoriesResponse")]
        System.Threading.Tasks.Task<my_progect.ServiceReference1.Categories> SelectByIdcategoriesAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Insertcategories", ReplyAction="http://tempuri.org/IService1/InsertcategoriesResponse")]
        void Insertcategories(my_progect.ServiceReference1.Categories p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Insertcategories", ReplyAction="http://tempuri.org/IService1/InsertcategoriesResponse")]
        System.Threading.Tasks.Task InsertcategoriesAsync(my_progect.ServiceReference1.Categories p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Updatecategories", ReplyAction="http://tempuri.org/IService1/UpdatecategoriesResponse")]
        void Updatecategories(my_progect.ServiceReference1.Categories p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Updatecategories", ReplyAction="http://tempuri.org/IService1/UpdatecategoriesResponse")]
        System.Threading.Tasks.Task UpdatecategoriesAsync(my_progect.ServiceReference1.Categories p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAllcity", ReplyAction="http://tempuri.org/IService1/SelectAllcityResponse")]
        my_progect.ServiceReference1.City[] SelectAllcity();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAllcity", ReplyAction="http://tempuri.org/IService1/SelectAllcityResponse")]
        System.Threading.Tasks.Task<my_progect.ServiceReference1.City[]> SelectAllcityAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectByIdcity", ReplyAction="http://tempuri.org/IService1/SelectByIdcityResponse")]
        my_progect.ServiceReference1.City SelectByIdcity(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectByIdcity", ReplyAction="http://tempuri.org/IService1/SelectByIdcityResponse")]
        System.Threading.Tasks.Task<my_progect.ServiceReference1.City> SelectByIdcityAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Insertcity", ReplyAction="http://tempuri.org/IService1/InsertcityResponse")]
        void Insertcity(my_progect.ServiceReference1.City p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Insertcity", ReplyAction="http://tempuri.org/IService1/InsertcityResponse")]
        System.Threading.Tasks.Task InsertcityAsync(my_progect.ServiceReference1.City p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Updatecity", ReplyAction="http://tempuri.org/IService1/UpdatecityResponse")]
        void Updatecity(my_progect.ServiceReference1.City city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Updatecity", ReplyAction="http://tempuri.org/IService1/UpdatecityResponse")]
        System.Threading.Tasks.Task UpdatecityAsync(my_progect.ServiceReference1.City city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAllcomments", ReplyAction="http://tempuri.org/IService1/SelectAllcommentsResponse")]
        my_progect.ServiceReference1.Comments[] SelectAllcomments();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAllcomments", ReplyAction="http://tempuri.org/IService1/SelectAllcommentsResponse")]
        System.Threading.Tasks.Task<my_progect.ServiceReference1.Comments[]> SelectAllcommentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Insertcomments", ReplyAction="http://tempuri.org/IService1/InsertcommentsResponse")]
        void Insertcomments(my_progect.ServiceReference1.Comments p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Insertcomments", ReplyAction="http://tempuri.org/IService1/InsertcommentsResponse")]
        System.Threading.Tasks.Task InsertcommentsAsync(my_progect.ServiceReference1.Comments p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Updatecomments", ReplyAction="http://tempuri.org/IService1/UpdatecommentsResponse")]
        void Updatecomments(my_progect.ServiceReference1.Comments p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Updatecomments", ReplyAction="http://tempuri.org/IService1/UpdatecommentsResponse")]
        System.Threading.Tasks.Task UpdatecommentsAsync(my_progect.ServiceReference1.Comments p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectByIdcomments", ReplyAction="http://tempuri.org/IService1/SelectByIdcommentsResponse")]
        my_progect.ServiceReference1.Comments SelectByIdcomments(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectByIdcomments", ReplyAction="http://tempuri.org/IService1/SelectByIdcommentsResponse")]
        System.Threading.Tasks.Task<my_progect.ServiceReference1.Comments> SelectByIdcommentsAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAllcostumer", ReplyAction="http://tempuri.org/IService1/SelectAllcostumerResponse")]
        my_progect.ServiceReference1.Costumer[] SelectAllcostumer();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAllcostumer", ReplyAction="http://tempuri.org/IService1/SelectAllcostumerResponse")]
        System.Threading.Tasks.Task<my_progect.ServiceReference1.Costumer[]> SelectAllcostumerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Insertcostumer", ReplyAction="http://tempuri.org/IService1/InsertcostumerResponse")]
        void Insertcostumer(my_progect.ServiceReference1.Costumer c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Insertcostumer", ReplyAction="http://tempuri.org/IService1/InsertcostumerResponse")]
        System.Threading.Tasks.Task InsertcostumerAsync(my_progect.ServiceReference1.Costumer c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Updatecostumer", ReplyAction="http://tempuri.org/IService1/UpdatecostumerResponse")]
        void Updatecostumer(my_progect.ServiceReference1.Costumer c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Updatecostumer", ReplyAction="http://tempuri.org/IService1/UpdatecostumerResponse")]
        System.Threading.Tasks.Task UpdatecostumerAsync(my_progect.ServiceReference1.Costumer c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectByIdcostumer", ReplyAction="http://tempuri.org/IService1/SelectByIdcostumerResponse")]
        my_progect.ServiceReference1.Costumer SelectByIdcostumer(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectByIdcostumer", ReplyAction="http://tempuri.org/IService1/SelectByIdcostumerResponse")]
        System.Threading.Tasks.Task<my_progect.ServiceReference1.Costumer> SelectByIdcostumerAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Insertpeople", ReplyAction="http://tempuri.org/IService1/InsertpeopleResponse")]
        void Insertpeople(my_progect.ServiceReference1.People p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Insertpeople", ReplyAction="http://tempuri.org/IService1/InsertpeopleResponse")]
        System.Threading.Tasks.Task InsertpeopleAsync(my_progect.ServiceReference1.People p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Updatepeople", ReplyAction="http://tempuri.org/IService1/UpdatepeopleResponse")]
        void Updatepeople(my_progect.ServiceReference1.People p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Updatepeople", ReplyAction="http://tempuri.org/IService1/UpdatepeopleResponse")]
        System.Threading.Tasks.Task UpdatepeopleAsync(my_progect.ServiceReference1.People p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAllseller", ReplyAction="http://tempuri.org/IService1/SelectAllsellerResponse")]
        my_progect.ServiceReference1.Seller[] SelectAllseller();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAllseller", ReplyAction="http://tempuri.org/IService1/SelectAllsellerResponse")]
        System.Threading.Tasks.Task<my_progect.ServiceReference1.Seller[]> SelectAllsellerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Insertseller", ReplyAction="http://tempuri.org/IService1/InsertsellerResponse")]
        void Insertseller(my_progect.ServiceReference1.Seller c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Insertseller", ReplyAction="http://tempuri.org/IService1/InsertsellerResponse")]
        System.Threading.Tasks.Task InsertsellerAsync(my_progect.ServiceReference1.Seller c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Updateseller", ReplyAction="http://tempuri.org/IService1/UpdatesellerResponse")]
        void Updateseller(my_progect.ServiceReference1.Seller c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Updateseller", ReplyAction="http://tempuri.org/IService1/UpdatesellerResponse")]
        System.Threading.Tasks.Task UpdatesellerAsync(my_progect.ServiceReference1.Seller c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectByIdsekller", ReplyAction="http://tempuri.org/IService1/SelectByIdsekllerResponse")]
        my_progect.ServiceReference1.Seller SelectByIdsekller(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectByIdsekller", ReplyAction="http://tempuri.org/IService1/SelectByIdsekllerResponse")]
        System.Threading.Tasks.Task<my_progect.ServiceReference1.Seller> SelectByIdsekllerAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAlltakendates", ReplyAction="http://tempuri.org/IService1/SelectAlltakendatesResponse")]
        my_progect.ServiceReference1.Takendates[] SelectAlltakendates();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAlltakendates", ReplyAction="http://tempuri.org/IService1/SelectAlltakendatesResponse")]
        System.Threading.Tasks.Task<my_progect.ServiceReference1.Takendates[]> SelectAlltakendatesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectByIdtakendates", ReplyAction="http://tempuri.org/IService1/SelectByIdtakendatesResponse")]
        my_progect.ServiceReference1.Takendates SelectByIdtakendates(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectByIdtakendates", ReplyAction="http://tempuri.org/IService1/SelectByIdtakendatesResponse")]
        System.Threading.Tasks.Task<my_progect.ServiceReference1.Takendates> SelectByIdtakendatesAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Inserttakendates", ReplyAction="http://tempuri.org/IService1/InserttakendatesResponse")]
        void Inserttakendates(my_progect.ServiceReference1.Takendates p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Inserttakendates", ReplyAction="http://tempuri.org/IService1/InserttakendatesResponse")]
        System.Threading.Tasks.Task InserttakendatesAsync(my_progect.ServiceReference1.Takendates p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Updatetakendates", ReplyAction="http://tempuri.org/IService1/UpdatetakendatesResponse")]
        void Updatetakendates(my_progect.ServiceReference1.Takendates p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Updatetakendates", ReplyAction="http://tempuri.org/IService1/UpdatetakendatesResponse")]
        System.Threading.Tasks.Task UpdatetakendatesAsync(my_progect.ServiceReference1.Takendates p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/selectbyphoneseller", ReplyAction="http://tempuri.org/IService1/selectbyphonesellerResponse")]
        my_progect.ServiceReference1.Seller selectbyphoneseller(string phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/selectbyphoneseller", ReplyAction="http://tempuri.org/IService1/selectbyphonesellerResponse")]
        System.Threading.Tasks.Task<my_progect.ServiceReference1.Seller> selectbyphonesellerAsync(string phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectByIdpeople", ReplyAction="http://tempuri.org/IService1/SelectByIdpeopleResponse")]
        my_progect.ServiceReference1.People SelectByIdpeople(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectByIdpeople", ReplyAction="http://tempuri.org/IService1/SelectByIdpeopleResponse")]
        System.Threading.Tasks.Task<my_progect.ServiceReference1.People> SelectByIdpeopleAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAllChat", ReplyAction="http://tempuri.org/IService1/SelectAllChatResponse")]
        my_progect.ServiceReference1.Chat[] SelectAllChat();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAllChat", ReplyAction="http://tempuri.org/IService1/SelectAllChatResponse")]
        System.Threading.Tasks.Task<my_progect.ServiceReference1.Chat[]> SelectAllChatAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertCat", ReplyAction="http://tempuri.org/IService1/InsertCatResponse")]
        void InsertCat(my_progect.ServiceReference1.Chat chat, my_progect.ServiceReference1.Seller writer, my_progect.ServiceReference1.Costumer accept);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertCat", ReplyAction="http://tempuri.org/IService1/InsertCatResponse")]
        System.Threading.Tasks.Task InsertCatAsync(my_progect.ServiceReference1.Chat chat, my_progect.ServiceReference1.Seller writer, my_progect.ServiceReference1.Costumer accept);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertCat1", ReplyAction="http://tempuri.org/IService1/InsertCat1Response")]
        void InsertCat1(my_progect.ServiceReference1.Chat chat, my_progect.ServiceReference1.Costumer writer, my_progect.ServiceReference1.Seller accept);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertCat1", ReplyAction="http://tempuri.org/IService1/InsertCat1Response")]
        System.Threading.Tasks.Task InsertCat1Async(my_progect.ServiceReference1.Chat chat, my_progect.ServiceReference1.Costumer writer, my_progect.ServiceReference1.Seller accept);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/selectbyphonecostumer", ReplyAction="http://tempuri.org/IService1/selectbyphonecostumerResponse")]
        my_progect.ServiceReference1.Costumer selectbyphonecostumer(string phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/selectbyphonecostumer", ReplyAction="http://tempuri.org/IService1/selectbyphonecostumerResponse")]
        System.Threading.Tasks.Task<my_progect.ServiceReference1.Costumer> selectbyphonecostumerAsync(string phone);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : my_progect.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<my_progect.ServiceReference1.IService1>, my_progect.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public my_progect.ServiceReference1.Business[] SelectAllbusiness() {
            return base.Channel.SelectAllbusiness();
        }
        
        public System.Threading.Tasks.Task<my_progect.ServiceReference1.Business[]> SelectAllbusinessAsync() {
            return base.Channel.SelectAllbusinessAsync();
        }
        
        public my_progect.ServiceReference1.Business SelectByIdbusiness(int id) {
            return base.Channel.SelectByIdbusiness(id);
        }
        
        public System.Threading.Tasks.Task<my_progect.ServiceReference1.Business> SelectByIdbusinessAsync(int id) {
            return base.Channel.SelectByIdbusinessAsync(id);
        }
        
        public void Insertbusiness(my_progect.ServiceReference1.Business p) {
            base.Channel.Insertbusiness(p);
        }
        
        public System.Threading.Tasks.Task InsertbusinessAsync(my_progect.ServiceReference1.Business p) {
            return base.Channel.InsertbusinessAsync(p);
        }
        
        public void Updatebusiness(my_progect.ServiceReference1.Business p) {
            base.Channel.Updatebusiness(p);
        }
        
        public System.Threading.Tasks.Task UpdatebusinessAsync(my_progect.ServiceReference1.Business p) {
            return base.Channel.UpdatebusinessAsync(p);
        }
        
        public my_progect.ServiceReference1.Categories[] SelectAllcategories() {
            return base.Channel.SelectAllcategories();
        }
        
        public System.Threading.Tasks.Task<my_progect.ServiceReference1.Categories[]> SelectAllcategoriesAsync() {
            return base.Channel.SelectAllcategoriesAsync();
        }
        
        public my_progect.ServiceReference1.Categories SelectByIdcategories(int id) {
            return base.Channel.SelectByIdcategories(id);
        }
        
        public System.Threading.Tasks.Task<my_progect.ServiceReference1.Categories> SelectByIdcategoriesAsync(int id) {
            return base.Channel.SelectByIdcategoriesAsync(id);
        }
        
        public void Insertcategories(my_progect.ServiceReference1.Categories p) {
            base.Channel.Insertcategories(p);
        }
        
        public System.Threading.Tasks.Task InsertcategoriesAsync(my_progect.ServiceReference1.Categories p) {
            return base.Channel.InsertcategoriesAsync(p);
        }
        
        public void Updatecategories(my_progect.ServiceReference1.Categories p) {
            base.Channel.Updatecategories(p);
        }
        
        public System.Threading.Tasks.Task UpdatecategoriesAsync(my_progect.ServiceReference1.Categories p) {
            return base.Channel.UpdatecategoriesAsync(p);
        }
        
        public my_progect.ServiceReference1.City[] SelectAllcity() {
            return base.Channel.SelectAllcity();
        }
        
        public System.Threading.Tasks.Task<my_progect.ServiceReference1.City[]> SelectAllcityAsync() {
            return base.Channel.SelectAllcityAsync();
        }
        
        public my_progect.ServiceReference1.City SelectByIdcity(int id) {
            return base.Channel.SelectByIdcity(id);
        }
        
        public System.Threading.Tasks.Task<my_progect.ServiceReference1.City> SelectByIdcityAsync(int id) {
            return base.Channel.SelectByIdcityAsync(id);
        }
        
        public void Insertcity(my_progect.ServiceReference1.City p) {
            base.Channel.Insertcity(p);
        }
        
        public System.Threading.Tasks.Task InsertcityAsync(my_progect.ServiceReference1.City p) {
            return base.Channel.InsertcityAsync(p);
        }
        
        public void Updatecity(my_progect.ServiceReference1.City city) {
            base.Channel.Updatecity(city);
        }
        
        public System.Threading.Tasks.Task UpdatecityAsync(my_progect.ServiceReference1.City city) {
            return base.Channel.UpdatecityAsync(city);
        }
        
        public my_progect.ServiceReference1.Comments[] SelectAllcomments() {
            return base.Channel.SelectAllcomments();
        }
        
        public System.Threading.Tasks.Task<my_progect.ServiceReference1.Comments[]> SelectAllcommentsAsync() {
            return base.Channel.SelectAllcommentsAsync();
        }
        
        public void Insertcomments(my_progect.ServiceReference1.Comments p) {
            base.Channel.Insertcomments(p);
        }
        
        public System.Threading.Tasks.Task InsertcommentsAsync(my_progect.ServiceReference1.Comments p) {
            return base.Channel.InsertcommentsAsync(p);
        }
        
        public void Updatecomments(my_progect.ServiceReference1.Comments p) {
            base.Channel.Updatecomments(p);
        }
        
        public System.Threading.Tasks.Task UpdatecommentsAsync(my_progect.ServiceReference1.Comments p) {
            return base.Channel.UpdatecommentsAsync(p);
        }
        
        public my_progect.ServiceReference1.Comments SelectByIdcomments(int id) {
            return base.Channel.SelectByIdcomments(id);
        }
        
        public System.Threading.Tasks.Task<my_progect.ServiceReference1.Comments> SelectByIdcommentsAsync(int id) {
            return base.Channel.SelectByIdcommentsAsync(id);
        }
        
        public my_progect.ServiceReference1.Costumer[] SelectAllcostumer() {
            return base.Channel.SelectAllcostumer();
        }
        
        public System.Threading.Tasks.Task<my_progect.ServiceReference1.Costumer[]> SelectAllcostumerAsync() {
            return base.Channel.SelectAllcostumerAsync();
        }
        
        public void Insertcostumer(my_progect.ServiceReference1.Costumer c) {
            base.Channel.Insertcostumer(c);
        }
        
        public System.Threading.Tasks.Task InsertcostumerAsync(my_progect.ServiceReference1.Costumer c) {
            return base.Channel.InsertcostumerAsync(c);
        }
        
        public void Updatecostumer(my_progect.ServiceReference1.Costumer c) {
            base.Channel.Updatecostumer(c);
        }
        
        public System.Threading.Tasks.Task UpdatecostumerAsync(my_progect.ServiceReference1.Costumer c) {
            return base.Channel.UpdatecostumerAsync(c);
        }
        
        public my_progect.ServiceReference1.Costumer SelectByIdcostumer(int id) {
            return base.Channel.SelectByIdcostumer(id);
        }
        
        public System.Threading.Tasks.Task<my_progect.ServiceReference1.Costumer> SelectByIdcostumerAsync(int id) {
            return base.Channel.SelectByIdcostumerAsync(id);
        }
        
        public void Insertpeople(my_progect.ServiceReference1.People p) {
            base.Channel.Insertpeople(p);
        }
        
        public System.Threading.Tasks.Task InsertpeopleAsync(my_progect.ServiceReference1.People p) {
            return base.Channel.InsertpeopleAsync(p);
        }
        
        public void Updatepeople(my_progect.ServiceReference1.People p) {
            base.Channel.Updatepeople(p);
        }
        
        public System.Threading.Tasks.Task UpdatepeopleAsync(my_progect.ServiceReference1.People p) {
            return base.Channel.UpdatepeopleAsync(p);
        }
        
        public my_progect.ServiceReference1.Seller[] SelectAllseller() {
            return base.Channel.SelectAllseller();
        }
        
        public System.Threading.Tasks.Task<my_progect.ServiceReference1.Seller[]> SelectAllsellerAsync() {
            return base.Channel.SelectAllsellerAsync();
        }
        
        public void Insertseller(my_progect.ServiceReference1.Seller c) {
            base.Channel.Insertseller(c);
        }
        
        public System.Threading.Tasks.Task InsertsellerAsync(my_progect.ServiceReference1.Seller c) {
            return base.Channel.InsertsellerAsync(c);
        }
        
        public void Updateseller(my_progect.ServiceReference1.Seller c) {
            base.Channel.Updateseller(c);
        }
        
        public System.Threading.Tasks.Task UpdatesellerAsync(my_progect.ServiceReference1.Seller c) {
            return base.Channel.UpdatesellerAsync(c);
        }
        
        public my_progect.ServiceReference1.Seller SelectByIdsekller(int id) {
            return base.Channel.SelectByIdsekller(id);
        }
        
        public System.Threading.Tasks.Task<my_progect.ServiceReference1.Seller> SelectByIdsekllerAsync(int id) {
            return base.Channel.SelectByIdsekllerAsync(id);
        }
        
        public my_progect.ServiceReference1.Takendates[] SelectAlltakendates() {
            return base.Channel.SelectAlltakendates();
        }
        
        public System.Threading.Tasks.Task<my_progect.ServiceReference1.Takendates[]> SelectAlltakendatesAsync() {
            return base.Channel.SelectAlltakendatesAsync();
        }
        
        public my_progect.ServiceReference1.Takendates SelectByIdtakendates(int id) {
            return base.Channel.SelectByIdtakendates(id);
        }
        
        public System.Threading.Tasks.Task<my_progect.ServiceReference1.Takendates> SelectByIdtakendatesAsync(int id) {
            return base.Channel.SelectByIdtakendatesAsync(id);
        }
        
        public void Inserttakendates(my_progect.ServiceReference1.Takendates p) {
            base.Channel.Inserttakendates(p);
        }
        
        public System.Threading.Tasks.Task InserttakendatesAsync(my_progect.ServiceReference1.Takendates p) {
            return base.Channel.InserttakendatesAsync(p);
        }
        
        public void Updatetakendates(my_progect.ServiceReference1.Takendates p) {
            base.Channel.Updatetakendates(p);
        }
        
        public System.Threading.Tasks.Task UpdatetakendatesAsync(my_progect.ServiceReference1.Takendates p) {
            return base.Channel.UpdatetakendatesAsync(p);
        }
        
        public my_progect.ServiceReference1.Seller selectbyphoneseller(string phone) {
            return base.Channel.selectbyphoneseller(phone);
        }
        
        public System.Threading.Tasks.Task<my_progect.ServiceReference1.Seller> selectbyphonesellerAsync(string phone) {
            return base.Channel.selectbyphonesellerAsync(phone);
        }
        
        public my_progect.ServiceReference1.People SelectByIdpeople(int id) {
            return base.Channel.SelectByIdpeople(id);
        }
        
        public System.Threading.Tasks.Task<my_progect.ServiceReference1.People> SelectByIdpeopleAsync(int id) {
            return base.Channel.SelectByIdpeopleAsync(id);
        }
        
        public my_progect.ServiceReference1.Chat[] SelectAllChat() {
            return base.Channel.SelectAllChat();
        }
        
        public System.Threading.Tasks.Task<my_progect.ServiceReference1.Chat[]> SelectAllChatAsync() {
            return base.Channel.SelectAllChatAsync();
        }
        
        public void InsertCat(my_progect.ServiceReference1.Chat chat, my_progect.ServiceReference1.Seller writer, my_progect.ServiceReference1.Costumer accept) {
            base.Channel.InsertCat(chat, writer, accept);
        }
        
        public System.Threading.Tasks.Task InsertCatAsync(my_progect.ServiceReference1.Chat chat, my_progect.ServiceReference1.Seller writer, my_progect.ServiceReference1.Costumer accept) {
            return base.Channel.InsertCatAsync(chat, writer, accept);
        }
        
        public void InsertCat1(my_progect.ServiceReference1.Chat chat, my_progect.ServiceReference1.Costumer writer, my_progect.ServiceReference1.Seller accept) {
            base.Channel.InsertCat1(chat, writer, accept);
        }
        
        public System.Threading.Tasks.Task InsertCat1Async(my_progect.ServiceReference1.Chat chat, my_progect.ServiceReference1.Costumer writer, my_progect.ServiceReference1.Seller accept) {
            return base.Channel.InsertCat1Async(chat, writer, accept);
        }
        
        public my_progect.ServiceReference1.Costumer selectbyphonecostumer(string phone) {
            return base.Channel.selectbyphonecostumer(phone);
        }
        
        public System.Threading.Tasks.Task<my_progect.ServiceReference1.Costumer> selectbyphonecostumerAsync(string phone) {
            return base.Channel.selectbyphonecostumerAsync(phone);
        }
    }
}
